#!/usr/bin/env python3
"""
One-off extraction: pull sender domains out of the phishing-labeled rows in
Nazario_5.csv's 'sender' column and write the ones that recur across
multiple emails to src/known_phishing_domains.py.

Deliberately Nazario-only, not SpamAssassin: SpamAssassin's "spam" label
means unsolicited bulk email in general, not phishing specifically -- an
earlier version of this script pulled from SpamAssassin's spam/ folders too
and the result was contaminated with legitimate mailing-list/project
domains (samba.org, apache.org, sourceforge.net, ...) that show up in bulk
mail but aren't phishing. Nazario is a phishing-specific corpus, so its
sender domains are a much higher-precision signal for this use.

This is NOT run at app runtime -- it's a build-time tool. Re-run it by hand
if the raw corpora under data/raw/ change.

Recurrence is required (not a single sighting) because spam/phishing "From"
addresses are routinely spoofed/randomized; a domain seen only once is more
likely noise than a real recurring pattern. Common free-mail providers are
excluded since phishers spoof them constantly but legitimate senders use
them too -- blocklisting gmail.com etc. would cause false positives.
"""
import csv
import os
import re
import sys
from collections import Counter

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import RAW_DATA_DIR

csv.field_size_limit(10_000_000)

MIN_OCCURRENCES = 2
MAX_DOMAINS = 500

EXCLUDED_PROVIDERS = {
    'gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'aol.com',
    'icloud.com', 'live.com', 'msn.com', 'mail.com', 'protonmail.com',
    'comcast.net', 'verizon.net', 'att.net',
}

EMAIL_RE = re.compile(r'[\w.+-]+@([\w-]+(?:\.[\w-]+)+)')


def domain_from_address(address):
    match = EMAIL_RE.search(address or '')
    return match.group(1).lower() if match else None


def extract_from_nazario(counter):
    """
    Nazario_5.csv is a *mixed* dataset -- label '1' rows are phishing, but
    label '0' rows are legitimate mail (specifically the Enron corpus).
    Skipping the label filter here previously made 'enron.com' look like
    the #1 phishing domain, when it was actually the most common
    *legitimate* sender in the file.
    """
    path = os.path.join(RAW_DATA_DIR, 'Nazario_5.csv')
    if not os.path.exists(path):
        print(f"  skip: {path} not found")
        return
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        reader = csv.DictReader(f)
        if 'sender' not in (reader.fieldnames or []):
            print("  skip: Nazario_5.csv has no 'sender' column")
            return
        skipped_legitimate = 0
        for row in reader:
            if row.get('label') != '1':
                skipped_legitimate += 1
                continue
            domain = domain_from_address(row.get('sender', ''))
            if domain:
                counter[domain] += 1
    print(f"  Nazario_5.csv: {sum(counter.values())} phishing sender domains "
          f"({skipped_legitimate} legitimate-labeled rows skipped)")


def main():
    counter = Counter()
    print("Extracting sender domains from the Nazario phishing corpus...")
    extract_from_nazario(counter)

    filtered = {
        domain: count for domain, count in counter.items()
        if count >= MIN_OCCURRENCES and domain not in EXCLUDED_PROVIDERS
    }
    top_domains = sorted(filtered.items(), key=lambda kv: -kv[1])[:MAX_DOMAINS]

    print(f"\n{len(counter)} unique domains seen, {len(filtered)} recur >= {MIN_OCCURRENCES}x, "
          f"keeping top {len(top_domains)}")

    output_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                'src', 'known_phishing_domains.py')
    with open(output_path, 'w') as f:
        f.write('"""\n')
        f.write('Sender domains that recurred across multiple phishing-labeled emails\n')
        f.write('in the Nazario corpus. Used as an offline fallback signal when live\n')
        f.write('DNS/MX verification is unavailable (see src/email_verifier.py).\n')
        f.write('Generated by scripts/extract_known_phishing_domains.py -- do not hand-edit.\n')
        f.write('"""\n\n')
        f.write('KNOWN_PHISHING_DOMAINS = frozenset({\n')
        for domain, count in top_domains:
            f.write(f"    {domain!r},  # seen {count}x\n")
        f.write('})\n')

    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
